// Opt-in documentation capture, excluded from the regression suite.
import { mkdirSync } from 'node:fs';
import { test, expect } from './fixtures';
test('record a 70-second UI walkthrough with simulated engine responses', async ({ page, extensionId }) => {
  test.setTimeout(120_000);
  mkdirSync('docs/media', { recursive: true });
  const hold = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
  const shot = (name: string) => page.screenshot({ path: `docs/media/${name}.png` });
  await page.goto('http://127.0.0.1:4173');
  await page.locator('#password').evaluate(el => { el.previousElementSibling?.remove(); el.remove(); });
  await page.locator('#draft').fill('Please recieve teh updated document today.');
  await expect(page.locator('.badge')).toHaveAttribute('data-state', 'issues');
  await hold(6000);
  await page.locator('.badge').click();
  await expect(page.getByRole('button', { name: 'Accept', exact: true })).toBeVisible();
  await shot('01-suggestion');
  await hold(8000);
  await page.getByRole('button', { name: 'Why?', exact: true }).click();
  await expect(page.getByText('This is a deterministic test explanation, not model output.')).toBeVisible();
  await hold(6000);
  await page.getByRole('button', { name: 'Accept', exact: true }).click();
  await shot('02-next-suggestion');
  await hold(6000);
  await page.getByRole('button', { name: 'Accept', exact: true }).click();
  await expect(page.locator('#draft')).toHaveValue('Please receive the updated document today.');
  await shot('03-corrected');
  await hold(6000);
  await page.locator('#rich').evaluate(el => { el.innerHTML = '<b>Please</b> recieve the document.<br><i>Thank you.</i>'; });
  await page.locator('#rich').click();
  await expect(page.locator('.badge')).toHaveAttribute('data-state', 'issues');
  await page.locator('.badge').click();
  await shot('04-rich-text');
  await hold(8000);
  await page.getByRole('button', { name: 'Accept', exact: true }).click();
  await expect(page.locator('#rich')).toContainText('receive');
  await hold(6000);
  await page.locator('#rich').press('ControlOrMeta+z');
  await expect(page.locator('#rich')).toContainText('recieve');
  await hold(6000);
  await page.goto(`chrome-extension://${extensionId}/options/index.html`);
  await page.locator('#dict-input').fill('Pilcrow');
  await page.locator('#dict-add').click();
  await expect(page.locator('#dictionary')).toContainText('Pilcrow');
  await shot('05-settings');
  await hold(8000);
  const video = page.video()!;
  await page.close();
  await video.saveAs('docs/media/ui-demo.webm');
});
